# Generated by Django 5.2.17 on 2026-09-30 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField()),
                ('kind', models.CharField(default='verify_document', editable=False, max_length=32)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(editable=False, null=True)),
                ('lease_until', models.DateTimeField(editable=False, null=True)),
                ('last_enqueued_at', models.DateTimeField(null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['state', 'last_enqueued_at'], name='job_dispatch_due')],
                'constraints': [models.UniqueConstraint(fields=('requested_by', 'operation_id'), name='one_job_operation_per_user'), models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='job_progress_percent')],
            },
        ),
    ]
